CREATE TABLE compta.user
(
    id       bigint NOT NULL,
    name     text   NOT NULL,
    password text   NOT NULL,
    email    text
);

CREATE TABLE compta.category
(
    id        bigint NOT NULL,
    id_user   bigint NOT NULL,
    name      text   NOT NULL,
    id_parent bigint
);

----------------------------------------------------------------------------------
--- Primary keys
----------------------------------------------------------------------------------
ALTER TABLE ONLY compta.user
    ADD CONSTRAINT user_pkey PRIMARY KEY (id);
ALTER TABLE ONLY compta.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


----------------------------------------------------------------------------------
--- Unique Constraints
----------------------------------------------------------------------------------
ALTER TABLE compta.user
    ADD CONSTRAINT unique_user_name UNIQUE (name);
ALTER TABLE compta.category
    ADD CONSTRAINT unique_category_name UNIQUE (id_user, name);

----------------------------------------------------------------------------------
--- Foreign Keys
----------------------------------------------------------------------------------
ALTER TABLE ONLY compta.category
    ADD CONSTRAINT fk_category FOREIGN KEY (id_parent) REFERENCES compta.category (id);
ALTER TABLE ONLY compta.category
    ADD CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES compta.user (id);

----------------------------------------------------------------------------------
--- Sequences
----------------------------------------------------------------------------------
ALTER TABLE compta.user
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME compta.user_id_seq
        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
        );

ALTER TABLE compta.category
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME compta.category_id_seq
        START WITH 1 INCREMENT BY 1 NO MINVALUE NO MAXVALUE CACHE 1
        );